[build]
  publish = "public"
  command = "npm ci --legacy-peer-deps && npm rebuild sharp --update-binary && npm run build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
  NODE_VERSION = "20.18.1"